jouday/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landing.urls')),
    path('admin/', admin.site.urls),
]

landing/urls.py
from django.urls import path

from . import views

app_name = 'landing'
urlpatterns = [
    path('', views.home, name='home'),
    path('services', views.services, name='services'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('rdv', views.rdv, name='rdv'),
    path('rdv/<int:id>', views.rdv, name='rdv_selected'),
    path('categories/<int:id>', views.categories, name='categories'),
]

landing/models.py
from django.db import models

# temoignages
class Temoignage(models.Model):
    nom = models.CharField(max_length=64)
    message = models.TextField()
    order = models.IntegerField(unique=True)
    

# categories
class Categorie(models.Model):
    nom = models.CharField(max_length=64)
    image = models.CharField(max_length=64)
    background_image = models.CharField(max_length=64)
    description = models.TextField()
    
    order_on_home = models.IntegerField(unique=True)
    
    def __str__(self):
        return f"{self.nom}"
    
    
# services
class Service(models.Model):
    categorie = models.ForeignKey(Categorie, on_delete = models.CASCADE, related_name="services")
    nom = models.CharField(max_length=64)
    prix = models.CharField(max_length=64)
    description = models.CharField(max_length=128, blank=True)
    
    def __str__(self):
        return f"{self.nom} - {self.prix}"
    
    
# contact
class Contact(models.Model):
    nom = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    
    sujet = models.CharField(max_length=64)
    message = models.TextField()
    
    date_heure_envoi = models.CharField(max_length=64)
    
    
# rendez-vous
class Rendez_vous(models.Model):
    nom = models.CharField(max_length=64)
    prenom = models.CharField(max_length=64)
    
    email = models.CharField(max_length=64, blank=True)
    numero = models.CharField(max_length=64)
    
    service = models.CharField(max_length=64)
    date_rdv = models.CharField(max_length=64)
    
    message = models.TextField(blank=True)
    date_heure_envoi = models.CharField(max_length=64)
    
    def __str__(self):
        return f"{self.prenom} : {self.service}"
    
    

# about
class About(models.Model):
    nom = models.CharField(max_length=64)
    
    numero = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    
    nom_insta = models.CharField(max_length=64)
    lien_insta = models.CharField(max_length=64)
    
    nom_facebook = models.CharField(max_length=64)
    lien_facebook = models.CharField(max_length=64)
    
    nom_tiktok = models.CharField(max_length=64)
    lien_tiktok = models.CharField(max_length=64)

    image = models.CharField(max_length=64)
    
    pourquoi_moi_image = models.CharField(max_length=64)
    
    quote = models.TextField()
    
    order = models.IntegerField(unique=True)
    
class About_Paragraphes(models.Model):
    paragraphe = models.TextField()
    order = models.IntegerField(unique=True)
    about = models.ForeignKey(About, on_delete = models.CASCADE, related_name="paragraphes")
    
class Pourquoi_moi_Paragraphes(models.Model):
    paragraphe = models.TextField()
    order = models.IntegerField(unique=True)
    about = models.ForeignKey(About, on_delete = models.CASCADE, related_name="pourquoi_paragraphes")
    
    
class HomeCarousel(models.Model):
    text = models.CharField(max_length=64)
    image = models.CharField(max_length=64)
    order = models.IntegerField(unique=True)

landing/views.py
from django.shortcuts import render
from .models import *

from django.http import JsonResponse

from datetime import datetime
from zoneinfo import ZoneInfo




# Create your views here.
def home(request):
    # ---------------get the person----------
    about = About.objects.all().order_by('order')
    about = about[0]
    
    # ------------Carousel--------------
    carousel = HomeCarousel.objects.all().order_by('order')[:3]
    for element in carousel:
        element.image = 'img/' + element.image
    
    # ---------categories--------------
    categories_all = Categorie.objects.all().order_by('order_on_home')
    for categorie in categories_all:
        categorie.service = categorie.services.all()
        categorie.image = 'img/' + categorie.image
        categorie.background_image = 'img/' + categorie.background_image
        
    # divide into 2
    length = len(categories_all)
    len1 = round(length / 2)
    
    class categorie_class():
        def __init__(self):
            self.categories = []
            self.length = 0
            
        def __str__(self):
            return (f'categories : {self.categories}, \nlength : {self.length}')
    
    # left
    left = categorie_class()
    
    for i in range(len1):
        left.categories.append(categories_all[i])
        left.categories[i].order = i + 1
        
    left.length = len(left.categories)
    
    
    # right
    right = categorie_class()
    
    for i in range(len1, length):
        j = i - len1
        right.categories.append(categories_all[i])
        right.categories[j].order = j + 1
        
    right.length = len(right.categories)
    
    
    
    # ------------testimonials-----------
    testimonials = Temoignage.objects.all().order_by('order')[:3]
    
    # -----------end------------
    return render(request, 'landing/home.html', {
        'carousel' : carousel,
        'left': left,
        'right': right,
        'testimonials' : testimonials,
        'about' : about,
        'home' : True
    })


def categories(request, id):
    # get the person
    about = About.objects.all().order_by('order')
    about = about[0]
    
    # categories
    categorie = Categorie.objects.get(id=id)
    categorie.image = 'img/' + categorie.image
    categorie.service = categorie.services.all()
    
    return render(request, 'landing/categories.html', {
        'about' : about,
        "categorie" : categorie
    })


def services(request):
    # get the person
    about = About.objects.all().order_by('order')
    about = about[0]
    
    # maquillage
    categories_maquillage = Categorie.objects.exclude(nom="Atelier auto-maquillage").all()
    for categorie in categories_maquillage:
        categorie.service = categorie.services.all()
    
    # atelier
    categories_atelier = Categorie.objects.get(nom="Atelier auto-maquillage")
    categories_atelier.service = categories_atelier.services.all()
    
    return render(request, 'landing/services.html', {
        "categories_maquillage" : categories_maquillage,
        "categories_atelier" : categories_atelier,
        'about' : about
    })


def about(request):
    # get the person
    about = About.objects.all().order_by('order')
    about = about[0]
    
    about.para = about.paragraphes.all().order_by('order')
    about.pourquoi_para = about.pourquoi_paragraphes.all().order_by('order')
    
    about.image = 'img/' + about.image
    about.pourquoi_moi_image = 'img/' + about.pourquoi_moi_image
    
    
    return render(request, 'landing/about.html', {
        "about" : about
    })


def contact(request):
    # get to page
    if request.method == 'GET':
        # get the person
        about = About.objects.all().order_by('order')
        about = about[0]
        
        return render(request, "landing/contact.html", {
            'about' : about
        })
    
    # submit form
    if request.method == 'POST':
        # get data
        nom = request.POST.get('nom')
        email = request.POST.get('email')
        
        sujet = request.POST.get('sujet')
        message = request.POST.get('message')
        
        date_heure_envoi = datetime.now(tz=ZoneInfo("Europe/Paris")).strftime("%d/%m/%Y - %H:%M:%S")
        
        # add to db
        added = Contact(nom=nom, email=email, sujet=sujet, message=message, date_heure_envoi=date_heure_envoi)
        added.save()
        
        # end
        return JsonResponse({
            "status" : "OK"
        })


def rdv(request, id=None):
    # get to page
    if request.method == 'GET':
        # get the person
        about = About.objects.all().order_by('order')
        about = about[0]
        
        # get categories
        categories = Categorie.objects.all()
        for categorie in categories:
            categorie.service = categorie.services.all()
            
        # select with id
        selected = None
        if id:
            selected = Service.objects.get(id=id)
        
        return render(request, "landing/rdv.html", {
            "categories" : categories,
            "selected" : selected,
            'about' : about
        })
    
    # submit form
    if request.method == 'POST':
        # get data
        nom = request.POST.get('nom')
        prenom = request.POST.get('prenom')
        
        email = request.POST.get('email')
        numero = request.POST.get('numero')
        
        date_rdv = request.POST.get('date_rdv')
        service = request.POST.get('service')
        
        message = request.POST.get('message')
        if not message:
            message = ''
            
        date_heure_envoi = datetime.now(tz=ZoneInfo("Europe/Paris")).strftime("%d/%m/%Y - %H:%M:%S")
        
        # add to db
        added = Rendez_vous(nom=nom, prenom=prenom, email=email, numero=numero, date_rdv=date_rdv, service=service,
                            message=message, date_heure_envoi=date_heure_envoi)
        added.save()
        
        # end
        return JsonResponse({
            "status" : "OK"
        })

landing/templates/landing/categories.html
{% extends 'landing/layout.html' %}


<!-- head -->
{% block head %}

    {% load static %}

    <!-- title -->
    <title>Catégorie : {{ categorie }}</title>

    <!-- page files -->
    <link rel="stylesheet" href="{% static 'css/categories.css' %}">
    <script src="{% static 'js/categories.js' %}"></script>

{% endblock %}


<!-- body -->
{% block body %}

    <!-- content -->
    <main>
        <!-- categorie -->
        <div id="categorie-page">
            <div id="title">
                <h1>Catégorie : {{ categorie.nom }}</h1>
            </div>
            <div id="infos_categorie">
                <div id="text_info">
                    <p>
                        {{ categorie.description }}
                    </p>
                </div>
                <div id="image_info">
                    <img src="{% static categorie.image %}" alt="">
                </div>
            </div>
        </div>
        <!-- services -->
        <div id="services">
            <!-- infos -->
            <div class="drop-down">
                <div class="drop-down-title-container">
                    <div class="drop-down-title">
                        <h2>Services et Tarifs</h2>
                    </div>
                    <div class="drop-down-svg-container">
                        <svg viewBox="0 0 20 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1.00057 14.9732H19.0006C19.1828 14.9727 19.3614 14.9224 19.5173 14.8279C19.6731 14.7333 19.8001 14.5981 19.8848 14.4367C19.9694 14.2753 20.0085 14.0939 19.9977 13.912C19.9869 13.73 19.9267 13.5545 19.8236 13.4042L10.8236 0.40425C10.4506 -0.13475 9.55257 -0.13475 9.17857 0.40425L0.178574 13.4042C0.0743986 13.5542 0.0133079 13.7298 0.00193892 13.912C-0.00943004 14.0943 0.0293576 14.2761 0.114088 14.4379C0.198818 14.5996 0.32625 14.735 0.482538 14.8294C0.638826 14.9238 0.817994 14.9735 1.00057 14.9732Z"
                            fill="#84847C"/>
                        </svg>   
                    </div>
                </div>
                <div class="drop-down-content">
                    {% for service in categorie.service %}
                        <div class="drop-down-info" id="{{ service.id }}"
                        onclick="window.location.pathname = '/rdv/' + this.id">
                            <div>
                                <p>{{ service.nom }}</p>

                                {% if service.description %}
                                    <em>{{ service.description | safe }}</em>
                                {% endif %}

                            </div>
                            
                            <span>{{ service.prix }}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>

{% endblock %}

landing/templates/landing/contact.html
{% extends 'landing/layout.html' %}


<!-- head -->
{% block head %}

    {% load static %}

    <!-- title -->
    <title>Contact</title>

    <!-- page files --> 
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <script src="{% static 'js/contact.js' %}"></script>

{% endblock %}

<!-- body -->
{% block body %}

    <!-- content -->
    <main>
        <div id="contact">
            <!-- infos -->
            <div id="informations">
                <div class="info" id="info-mob">
                    <p class="header">CALL <span id="tiret">-</span> EMAIL</p>
                    <p style="cursor: pointer;" onclick="window.location.href='tel:{{ about.numero }}';">
                        {{ about.numero }}
                    </p>
                    <p style="cursor: pointer;" onclick="window.location.href='mailto:{{ about.email }}';">
                        {{ about.email }}
                    </p>
                </div>

                <div class="info">
                    <p class="header">CALL US</p>
                    <p style="cursor: pointer;" onclick="window.location.href='tel:{{ about.numero }}';">
                        {{ about.numero }}
                    </p>
                </div>

                <div id="or">
                    <p>OR</p>
                </div>

                <div class="info">
                    <p class="header">EMAIL US</p>
                    <p style="cursor: pointer;" onclick="window.location.href='mailto:{{ about.email }}';">
                        {{ about.email }}
                    </p>
                </div>
            </div>

            <!-- form -->   
            <div id="form">
                <form action="{% url 'landing:contact' %}" method="post" class="contact1-form validate-form">
                    {% csrf_token %}
                    <div id="titre">
                        <h1>CONTACT</h1>
                        <p class="intro">Vous posez-vous des questions ou
                            voulez-vous nous faire savoir quelque chose&nbsp;?</p>
                    </div>

                    <div class="wrap-input1 validate-input" data-validate = "Name is required">
                        <input autocomplete="off" class="input1" type="text" name="nom" placeholder="Nom*">
                        <span class="shadow-input1"></span>
                    </div>

                    <div class="wrap-input1 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                        <input autocomplete="off" class="input1" type="email" name="email" placeholder="Email*">
                        <span class="shadow-input1"></span>
                    </div>

                    <div class="wrap-input1 validate-input" data-validate = "Subject is required">
                        <input autocomplete="off" class="input1" type="text" name="sujet" placeholder="Sujet*">
                        <span class="shadow-input1"></span>
                    </div>

                    <div class="wrap-input1 validate-input" data-validate = "Message is required">
                        <textarea autocomplete="off" class="input1" name="message" placeholder="Message*"></textarea>
                        <span class="shadow-input1"></span>
                    </div>

                    <div class="container-contact1-form-btn">
                        <button class="contact1-form-btn">
                            <span>
                                Envoyer
                                <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            </span>
                        </button>
                    </div>
                    <p id="status"></p>
                </form>
            </div>

            <!-- follow us -->
            <div id="follow">
                <p class="header">FOLLOW US</p>
                <p>
                    <span class="social_network_name">Facebook : </span>
                    <span onclick="window.open('{{ about.lien_facebook }}', '_blank');" style="cursor: pointer;">
                        {{ about.nom_facebook }}
                    </span>
                </p>
                <p onclick="window.open('{{ about.lien_insta }}', '_blank');">
                    <span class="social_network_name">Instagram : </span>
                    <span onclick="window.open('{{ about.lien_insta }}', '_blank');" style="cursor: pointer;">
                        {{ about.nom_insta }}
                    </span>
                </p>
            </div>
        </div>
    </main>
                
{% endblock %}

landing/templates/landing/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}

    <!-- page files -->
    {% block head %}{% endblock %}

    <!-- favicon -->
    <link rel="icon" href="{% static 'img/logo_icone_clair.png' %}">
    
    <!-- nav -->
    <link rel="stylesheet" href="/static/nav/nav.css">
    <script src="{% static 'nav/nav.js' %}"></script>
    <!-- footer -->
    <link rel="stylesheet" href="{% static 'footer/footer.css' %}">
</head>
<body>

    {% block before_nav %}{% endblock %}

    <!-- Nav -->
    <nav>
        <div id="nav_marque">
            <a href="{% url 'landing:home' %}">
                <img src="{% static 'img/logo.jpg' %}" style="border-radius: 100%;" alt="">
                <!-- <p style="margin: 0;">Makeup</p> -->
                <!-- <p style="margin: 0; font-size: 1rem;">By YAM</p> -->
            </a>
        </div>
        
        <button id="nav_button">
            <img src="{% static 'nav/menu.png' %}" alt="menu">
        </button>

        <div id="nav_add">
            <a id="nav_home" class="nav_el" href="{% url 'landing:home' %}">Accueil</a>
            <a id="nav_services" class="nav_el" href="{% url 'landing:services' %}">Services</a>
            <a id="nav_rdv" class="nav_el" href="{% url 'landing:rdv' %}">Rendez-vous</a>
            <a id="nav_contact" class="nav_el" href="{% url 'landing:contact' %}">Contact</a>
            <a id="nav_about" class="nav_el" href="{% url 'landing:about' %}">A propos</a>
        </div>

        <div id="nav-social">
            <!-- facebook -->
            <svg viewBox="0 0 11 20" fill="none" xmlns="http://www.w3.org/2000/svg"
            onclick="window.open('{{ about.lien_facebook }}', '_blank');">
                <path d="M7 11.5H9.5L10.5 7.5H7V5.5C7 4.47 7 3.5 9 3.5H10.5V0.14C10.174 0.0970001 8.943 0 7.643 0C4.928 0 3 1.657 3 4.7V7.5H0V11.5H3V20H7V11.5Z"
                fill="#84847C"/>
            </svg>
            <!-- sep -->
            <div class="nav-separator"></div>
            <!-- instagram -->
            <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"
            onclick="window.open('{{ about.lien_insta }}', '_blank');">
                <path d="M5.8 0H14.2C17.4 0 20 2.6 20 5.8V14.2C20 15.7383 19.3889 17.2135 18.3012 18.3012C17.2135 19.3889 15.7383 20 14.2 20H5.8C2.6 20 0 17.4 0 14.2V5.8C0 4.26174 0.61107 2.78649 1.69878 1.69878C2.78649 0.61107 4.26174 0 5.8 0ZM5.6 2C4.64522 2 3.72955 2.37928 3.05442 3.05442C2.37928 3.72955 2 4.64522 2 5.6V14.4C2 16.39 3.61 18 5.6 18H14.4C15.3548 18 16.2705 17.6207 16.9456 16.9456C17.6207 16.2705 18 15.3548 18 14.4V5.6C18 3.61 16.39 2 14.4 2H5.6ZM15.25 3.5C15.5815 3.5 15.8995 3.6317 16.1339 3.86612C16.3683 4.10054 16.5 4.41848 16.5 4.75C16.5 5.08152 16.3683 5.39946 16.1339 5.63388C15.8995 5.8683 15.5815 6 15.25 6C14.9185 6 14.6005 5.8683 14.3661 5.63388C14.1317 5.39946 14 5.08152 14 4.75C14 4.41848 14.1317 4.10054 14.3661 3.86612C14.6005 3.6317 14.9185 3.5 15.25 3.5ZM10 5C11.3261 5 12.5979 5.52678 13.5355 6.46447C14.4732 7.40215 15 8.67392 15 10C15 11.3261 14.4732 12.5979 13.5355 13.5355C12.5979 14.4732 11.3261 15 10 15C8.67392 15 7.40215 14.4732 6.46447 13.5355C5.52678 12.5979 5 11.3261 5 10C5 8.67392 5.52678 7.40215 6.46447 6.46447C7.40215 5.52678 8.67392 5 10 5ZM10 7C9.20435 7 8.44129 7.31607 7.87868 7.87868C7.31607 8.44129 7 9.20435 7 10C7 10.7956 7.31607 11.5587 7.87868 12.1213C8.44129 12.6839 9.20435 13 10 13C10.7956 13 11.5587 12.6839 12.1213 12.1213C12.6839 11.5587 13 10.7956 13 10C13 9.20435 12.6839 8.44129 12.1213 7.87868C11.5587 7.31607 10.7956 7 10 7Z"
                fill="#84847C"/>
            </svg>
            <!-- sep -->
            <div class="nav-separator"></div>
            <!-- tiktok -->
            <svg viewBox="0 0 17 18" fill="none" xmlns="http://www.w3.org/2000/svg"
            onclick="window.open('{{ about.lien_tiktok }}', '_blank');">
                <path d="M13.1002 2.82C12.4166 2.03962 12.0399 1.03743 12.0402 0H8.95016V12.4C8.92632 13.071 8.64303 13.7066 8.15992 14.1729C7.67682 14.6393 7.0316 14.8999 6.36016 14.9C4.94016 14.9 3.76016 13.74 3.76016 12.3C3.76016 10.58 5.42016 9.29 7.13016 9.82V6.66C3.68016 6.2 0.660156 8.88 0.660156 12.3C0.660156 15.63 3.42016 18 6.35016 18C9.49016 18 12.0402 15.45 12.0402 12.3V6.01C13.2932 6.90985 14.7975 7.39265 16.3402 7.39V4.3C16.3402 4.3 14.4602 4.39 13.1002 2.82Z"
                fill="#84847C"/>
            </svg>
        </div>
    </nav>

    {% block body %}{% endblock %}

    <!-- footer -->
    <footer>
        <!-- details -->
        <div id="footer_details">
            <!-- follow me -->
            <div id="footer-follow">
                <div class="footer-title">
                    <p id="footer-follow_me">FOLLOW US</p>
                </div>
                <div id="footer-social">
                    <!-- facebook -->
                    <svg viewBox="0 0 11 20" fill="none" xmlns="http://www.w3.org/2000/svg"
                    onclick="window.open('{{ about.lien_facebook }}', '_blank');">
                        <path d="M7 11.5H9.5L10.5 7.5H7V5.5C7 4.47 7 3.5 9 3.5H10.5V0.14C10.174 0.0970001 8.943 0 7.643 0C4.928 0 3 1.657 3 4.7V7.5H0V11.5H3V20H7V11.5Z"
                        fill="#84847C"/>
                    </svg>
                    <!-- sep -->
                    <div class="footer-separator"></div>
                    <!-- instagram -->
                    <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"
                    onclick="window.open('{{ about.lien_insta }}', '_blank');">
                        <path d="M5.8 0H14.2C17.4 0 20 2.6 20 5.8V14.2C20 15.7383 19.3889 17.2135 18.3012 18.3012C17.2135 19.3889 15.7383 20 14.2 20H5.8C2.6 20 0 17.4 0 14.2V5.8C0 4.26174 0.61107 2.78649 1.69878 1.69878C2.78649 0.61107 4.26174 0 5.8 0ZM5.6 2C4.64522 2 3.72955 2.37928 3.05442 3.05442C2.37928 3.72955 2 4.64522 2 5.6V14.4C2 16.39 3.61 18 5.6 18H14.4C15.3548 18 16.2705 17.6207 16.9456 16.9456C17.6207 16.2705 18 15.3548 18 14.4V5.6C18 3.61 16.39 2 14.4 2H5.6ZM15.25 3.5C15.5815 3.5 15.8995 3.6317 16.1339 3.86612C16.3683 4.10054 16.5 4.41848 16.5 4.75C16.5 5.08152 16.3683 5.39946 16.1339 5.63388C15.8995 5.8683 15.5815 6 15.25 6C14.9185 6 14.6005 5.8683 14.3661 5.63388C14.1317 5.39946 14 5.08152 14 4.75C14 4.41848 14.1317 4.10054 14.3661 3.86612C14.6005 3.6317 14.9185 3.5 15.25 3.5ZM10 5C11.3261 5 12.5979 5.52678 13.5355 6.46447C14.4732 7.40215 15 8.67392 15 10C15 11.3261 14.4732 12.5979 13.5355 13.5355C12.5979 14.4732 11.3261 15 10 15C8.67392 15 7.40215 14.4732 6.46447 13.5355C5.52678 12.5979 5 11.3261 5 10C5 8.67392 5.52678 7.40215 6.46447 6.46447C7.40215 5.52678 8.67392 5 10 5ZM10 7C9.20435 7 8.44129 7.31607 7.87868 7.87868C7.31607 8.44129 7 9.20435 7 10C7 10.7956 7.31607 11.5587 7.87868 12.1213C8.44129 12.6839 9.20435 13 10 13C10.7956 13 11.5587 12.6839 12.1213 12.1213C12.6839 11.5587 13 10.7956 13 10C13 9.20435 12.6839 8.44129 12.1213 7.87868C11.5587 7.31607 10.7956 7 10 7Z"
                        fill="#84847C"/>
                    </svg>
                    <!-- sep -->
                    <div class="footer-separator"></div>
                    <!-- tiktok -->
                    <svg viewBox="0 0 17 18" fill="none" xmlns="http://www.w3.org/2000/svg"
                    onclick="window.open('{{ about.lien_tiktok }}', '_blank');">
                        <path d="M13.1002 2.82C12.4166 2.03962 12.0399 1.03743 12.0402 0H8.95016V12.4C8.92632 13.071 8.64303 13.7066 8.15992 14.1729C7.67682 14.6393 7.0316 14.8999 6.36016 14.9C4.94016 14.9 3.76016 13.74 3.76016 12.3C3.76016 10.58 5.42016 9.29 7.13016 9.82V6.66C3.68016 6.2 0.660156 8.88 0.660156 12.3C0.660156 15.63 3.42016 18 6.35016 18C9.49016 18 12.0402 15.45 12.0402 12.3V6.01C13.2932 6.90985 14.7975 7.39265 16.3402 7.39V4.3C16.3402 4.3 14.4602 4.39 13.1002 2.82Z"
                        fill="#84847C"/>
                    </svg>
                </div>
                <p id="footer-miss_news">TO NOT MISS ANY NEWS!</p>
            </div>
            <div class="footer-divider"></div>
            <!-- customer service -->
            <div id="footer-customer">
                <div class="footer-title">
                    <p id="footer-custom_serv">CUSTOMER SERVICE</p>
                </div>
                <p><a href="{% url 'landing:about' %}">À PROPOS</a></p>
                <p><a href="{% url 'landing:contact' %}">CONTACTEZ-NOUS</a></p>
                <p><a href="{% url 'landing:rdv' %}">PRENDRE RDV</a></p>
            </div>
            <div class="footer-divider"></div>
            <!-- contact -->
            <div id="footer-contact">
                <div class="footer-title">
                    <p id="footer-contact_now">CONTACTS</p>
                </div>
                <p>{{ about.email }}</p>
                <p>{{ about.numero }}</p>
            </div>
        </div>
        <!-- copy right -->
        <div id="footer-copyright">
            <p>&copy; <span id="footer-year">2024</span> Copyright - www.makeup-yam.com</p>
            <script>
                document.addEventListener('DOMContentLoaded', ()=> {
                    const d = new Date();
                    let year = d.getFullYear();
                    document.getElementById('footer-year').innerText = year.toString();
                });
            </script>
        </div>
    </footer>

</body>
</html>